# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [4]:
import numpy as np

2. Create a null vector of size 10 

In [9]:
null_vetor=np.zeros(10)
null_vetor

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [ ]:
vector_array=np.arange(10,50)
vector_array


4. Find the shape of previous array in question 3

In [ ]:
print("Shape of the aarray : ",vector_array.shape)


5. Print the type of the previous array in question 3

In [ ]:
rint("Type of the Array : ",type(vector_array))


6. Print the numpy version and the configuration


In [ ]:
print(np.__version__)
print(np.show_config())

7. Print the dimension of the array in question 3


In [ ]:
print("Dimension of the Array : ",vector_array.ndim)

8. Create a boolean array with all the True values

In [ ]:
boolean_array=np.ones(10,dtype=bool)
boolean_array


9. Create a two dimensional array




In [ ]:
two_dimensional_array=np.arange(1,11).reshape(2,5)
two_dimensional_array

10. Create a three dimensional array



In [ ]:
three_dimensional_array=np.arange(1,13).reshape(3,4)
three_dimensional_array


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [ ]:
reverse_array=np.arange(1,11)
reverse_array[::-1]


12. Create a null vector of size 10 but the fifth value which is 1 

In [ ]:
null_vector_2=np.zeros(10)
null_vector_2[4]=1
null_vector_2

13. Create a 3x3 identity matrix

In [ ]:
identity_matrix=np.identity(3)
identity_matrix

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [10]:
arr = np.array([1, 2, 3, 4, 5])

arr.astype(np.float)


array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 =np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
np.multiply(arr1,arr2)


array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

comparisiion=(arr1==arr2)
equal_array=comparisiion.all()
print(equal_array)

False


17. Extract all odd numbers from arr with values(0-9)

In [17]:
arr[arr%2==1]

array([1, 3, 5])

18. Replace all odd numbers to -1 from previous array

In [18]:
arr[arr%2==1]=-1
arr1[arr1%2==1]=-1
arr2[arr2%2==1]=-1

print(arr)
print(arr1)
print(arr2)

[-1  2 -1  4 -1]
[[-1.  2. -1.]
 [ 4. -1.  6.]]
[[ 0.  4. -1.]
 [-1.  2. 12.]]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[5:9]=12
print(arr)


[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [ ]:
array_1=np.ones((5,5))
array_1[1:-1,1:-1]=0
print(array_1)

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [49]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],  [7, 8, 9]])
arr2d[arr2d==5]=12
print(arr2d)


[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [20]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0]=64
print(arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [ ]:
array_2d=np.arange(0,10).reshape(2,5)
array_2d[0]

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [21]:
array2d=np.arange(0,10)
array2d=array2d.reshape(2,5)
print("2nd value from 2nd 1-D array : ",array2d[1,1])

2nd value from 2nd 1-D array :  6


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [22]:
array2d[:,[2]]

array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [23]:
random_array=np.random.random((10,10))
print("Maximum ;",random_array.max())
print("Minimium :",random_array.min())

Maximum ; 0.9474521181936909
Minimium : 0.00016600902568097986


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
comman_item=a[a==b]
print(comman_item)

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [26]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(np.in1d(a, b))[0]


array([1, 3, 5, 7], dtype=int64)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [32]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
new_array=data[str(data)!="Will"]
new_array


array([[[-5.66582417e-01,  1.01473995e+00,  3.61467009e-01,
          5.53694117e-01],
        [-3.56340784e-01,  1.62262656e+00, -1.93051390e+00,
         -5.79317858e-01],
        [-6.26346043e-01, -1.57578725e-01, -1.00490870e+00,
         -5.27172976e-01],
        [-1.33145218e+00,  1.30876063e+00,  4.81330146e-01,
         -1.07994750e-01],
        [-1.90998931e+00,  9.67436821e-01, -7.43952060e-01,
          1.47916710e-01],
        [ 1.45386988e+00,  1.92345728e-03,  1.19932007e+00,
          1.56163763e+00],
        [-6.88090062e-01, -9.13800708e-01,  1.62666384e+00,
         -1.52182204e+00]]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [33]:
new_array=data[str(data)!="Will" and str(data)!="Joe"]
new_array

array([[[-5.66582417e-01,  1.01473995e+00,  3.61467009e-01,
          5.53694117e-01],
        [-3.56340784e-01,  1.62262656e+00, -1.93051390e+00,
         -5.79317858e-01],
        [-6.26346043e-01, -1.57578725e-01, -1.00490870e+00,
         -5.27172976e-01],
        [-1.33145218e+00,  1.30876063e+00,  4.81330146e-01,
         -1.07994750e-01],
        [-1.90998931e+00,  9.67436821e-01, -7.43952060e-01,
          1.47916710e-01],
        [ 1.45386988e+00,  1.92345728e-03,  1.19932007e+00,
          1.56163763e+00],
        [-6.88090062e-01, -9.13800708e-01,  1.62666384e+00,
         -1.52182204e+00]]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [34]:
array_2=np.arange(1,16)
array_2.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [35]:
array_2=np.arange(1,16)
array_2.reshape(5,3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

33. Swap axes of the array you created in Question 32

In [36]:
array_3=np.arange(1,17).reshape(2,2,4)
array_3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [37]:
np.swapaxes(array_3,0,2)

array([[[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]],

       [[ 4, 12],
        [ 8, 16]]])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [38]:
array_4=np.random.random((10))
array_4[array_4<0.5]=0
array_4

array([0.        , 0.82313103, 0.86644907, 0.53650724, 0.83239062,
       0.        , 0.        , 0.5292935 , 0.92962159, 0.98417739])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [52]:
unique_name=np.unique(names)
np.sort(unique_name)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [47]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
boolean_values=np.in1d(a,b)
a[~boolean_values]

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [44]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([10,10,10])
sampleArray[2]=newColumn
sampleArray


array([[34, 43, 73],
       [82, 22, 12],
       [10, 10, 10]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [43]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])

np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [ ]:
array_6=np.random.random((20))
np.cumsum(array_6)